name: Create Archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: papeloto/action-zip@v1
        with:
          files: plugin-development-assistant/
          dest: plugin-development-assistant

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'plugin-development-assistant.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
